apiVersion: iter8.tools/v2alpha2
kind: Experiment
metadata:
  name: istio-quickstart-exp
spec:
  # target identifies the knative service under experimentation using its fully qualified name
  target: bookinfo-iter8/reviews
  strategy:
    # this experiment will perform a canary test
    testingPattern: Canary
    deploymentPattern: Progressive
    actions:
      start: # run the following sequence of tasks at the start of the experiment
      - task: common/exec
        with:
          disableInterpolation: true
          cmd: /bin/sh
          args:
          - -c
          - |
            echo "Istio start action {{ .name }} {{ .version }} {{ .namespace }}"
            # kubectl -n {{ .namespace }}
      finish: # run the following sequence of tasks at the end of the experiment
      - task: common/exec
        with:
          cmd: /bin/bash
          args: 
          - "-c"
          - |
            echo "Istio finish action called"

            set -x

            # Read variables from versionInfo
            APPLICATION={{ .app }}
            VERSION_TO_PROMOTE={{ .version }}
            NAMESPACE={{ .namespace }}

            # Define constants
            TEMPLATE="https://raw.githubusercontent.com/kalantar/i8-istio/samples/canary/vs-final.yaml"
            
            # echo inputs
            echo "       APPLICATION = ${APPLICATION}"
            echo "VERSION_TO_PROMOTE = ${VERSION_TO_PROMOTE}"
            echo "         NAMESPACE = ${NAMESPACE}"
            echo "          TEMPLATE = ${TEMPLATE}"

            # fetch, modify and apply the template
            wget -q -O- ${TEMPLATE} | sed -e "s#subset:.*#subset: ${APPLICATION}-${VERSION_TO_PROMOTE}#" | kubectl -n ${NAMESPACE} apply -f -
            
            # log debug information
            kubectl -n ${NAMESPACE} get vs,dr
            kubectl -n ${NAMESPACE} get vs reviews -o json | jq .spec.http[0].route

            ## TBD would like to delete old destination rule

            set +x

            echo "Istio final action completed"

  criteria:
    # mean latency of version should be under 50 milliseconds
    # 95th percentile latency should be under 100 milliseconds
    # error rate should be under 1%
    objectives: 
    - metric: iter8-istio/mean-latency
      upperLimit: 50
    # - metric: 95th-percentile-tail-latency
    #   upperLimit: 100
    - metric: iter8-istio/error-rate
      upperLimit: "0.01"
  duration:
    intervalSeconds: 10
    iterationsPerLoop: 5
  versionInfo:
    # information about app versions used in this experiment
    baseline:
      name: baseline
      variables:
      - name: app
        value: reviews
      - name: version
        value: v2
      - name: revision
        value: reviews-v2
      - name: namespace
        value: bookinfo-iter8
      weightObjRef:
        apiVersion: networking.istio.io/v1beta1
        kind: VirtualService
        namespace: bookinfo-iter8
        name: reviews
        fieldPath: .spec.http[0].route[0].weight
    candidates:
    - name: candidate
      variables:
      - name: app
        value: reviews
      - name: version
        value: v3
      - name: revision
        value: reviews-v3
      - name: namespace
        value: bookinfo-iter8
      weightObjRef:
        apiVersion: networking.istio.io/v1beta1
        kind: VirtualService
        namespace: bookinfo-iter8
        name: reviews
        fieldPath: .spec.http[0].route[1].weight
