apiVersion: iter8.tools/v2alpha2
kind: Experiment
metadata:
  name: istio-service-canary-exp
spec:
  # target identifies the knative service under experimentation using its fully qualified name
  target: bookinfo-iter8/productpage
  strategy:
    # this experiment will perform a canary test
    testingPattern: Canary
    deploymentPattern: Progressive
    actions:
      start: # run the following sequence of tasks at the start of the experiment
      - task: common/exec
        with:
          disableInterpolation: true
          cmd: /bin/sh
          args:
          - -c
          - |
            echo "Istio start task called"
            echo "Nothing to do; assume that the VirtualService has already been suitably configured."
            echo "That is, it already has routes for each Service."
            echo "Istio start task complete"

      finish: # run the following sequence of tasks at the end of the experiment
      - task: common/exec
        with:
          cmd: /bin/bash
          args: 
          - "-c"
          - |
            echo "Istio finish task called"
            set -x

            # Read variables from versionInfo
            APPLICATION={{ .app }}
            VERSION_TO_PROMOTE={{ .version }}
            NAMESPACE={{ .namespace }}

            # Define constants
            VS="bookinfo"

            # echo inputs
            echo "       APPLICATION = ${APPLICATION}"
            echo "VERSION_TO_PROMOTE = ${VERSION_TO_PROMOTE}"
            echo "         NAMESPACE = ${NAMESPACE}"
            echo "                VS = ${VS}"

            # patch virtualservice
            kubectl patch vs ${VS} -n ${NAMESPACE} --type "json" -p "[{\"op\":\"add\", \"path\":\"/spec/http/0/route\", \"value\": [{\"destination\": { \"host\": \"${APPLICATION}\", \"port\": { \"number\": 9080 }, \"subset\": \"${APPLICATION}-${VERSION_TO_PROMOTE}\" }, \"weight\": 100}] }]"

            # log debug information
            kubectl -n ${NAMESPACE} get vs ${VS} -o json | jq .spec.http[0].route

            set +x
            echo "Istio final task completed"

  criteria:
    objectives: 
    - metric: iter8-istio/mean-latency
      upperLimit: 50
    - metric: iter8-istio/error-rate
      upperLimit: "0.01"
  duration:
    intervalSeconds: 10
    iterationsPerLoop: 8
  versionInfo:
    # information about app versions used in this experiment
    baseline:
      name: baseline
      variables:
      - name: app
        value: productpage
      - name: version
        value: v1
      - name: revision
        value: productpage-v1
      - name: namespace
        value: bookinfo-iter8
      weightObjRef:
        apiVersion: networking.istio.io/v1beta1
        kind: VirtualService
        namespace: bookinfo-iter8
        name: bookinfo
        fieldPath: .spec.http[0].route[0].weight
    candidates:
    - name: candidate
      variables:
      - name: app
        value: productpage
      - name: version
        value: v3
      - name: revision
        value: productpage-v3
      - name: namespace
        value: bookinfo-iter8
      weightObjRef:
        apiVersion: networking.istio.io/v1beta1
        kind: VirtualService
        namespace: bookinfo-iter8
        name: bookinfo
        fieldPath: .spec.http[0].route[1].weight