apiVersion: iter8.tools/v2alpha2
kind: Metric
metadata:
  name: books-purchased
spec:
  description: Total number of books purchased
  params:
  - name: query
    value: |
      sum(increase(number_of_books_purchased_total{destination_workload='$revision',destination_workload_namespace='$namespace'}[$elapsedTime])) or on() vector(0)
  type: counter
  provider: prometheus
  jqExpression: ".data.result[0].value[1] | tonumber"
  urlTemplate: http://prometheus-operated.iter8-system:9090/api/v1/query
